on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send repo to Dataverse
        uses: IQSS/dataverse-uploader@v1.6
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://dataverse.tdl.org
          DATAVERSE_DATASET_DOI: doi:10.18738/T8/F21TUO
          DELETE: False
